### ISSUE TITLE
Cadastro de telefones

### ISSUE THREAD

**Issue by paulolieuthier** [LuizVasconcelos/ProjetoBD#1]
Nas páginas relacionadas a funcionários e fornecedores, não são mostrados nem cadastrados os números de telefones dos indivíduos.

**Comment by LuizVasconcelos** [comment]
Consegui fazer cadastrar com 1 telefone, já verifiquei e as informações chegaram no banco, só preciso fazer alguns ajustes (isso pra funcionários). Depois botar pra ser possível mais de um telefone.

**Comment by paulolieuthier** [comment]
Massa! Se quiser, bota numa branch separada pra gente ver.

**Comment by LuizVasconcelos** [comment]
Coloco mais tarde que agora tô no estágio :p

**Comment by paulolieuthier** [comment]
Terminado em 1258d09e1b2f77b98325dc9d6b3b2ec75b169255. Valeu @LuizVasconcelos!

**Comment by miguelarauj1o** [comment]
@LuizVasconcelos :+1:
