### ISSUE TITLE
Erro ao clicar em botão "view and edit"

### ISSUE THREAD

**Issue by miguelarauj1o** [LuizVasconcelos/ProjetoBD#2]
Quando o botão "view and edit" é clicado, independente de qual opção estamos trabalhando, o seguinte erro é levantado:
`Fatal error: Call to a member function get_product_by_id() on null in /Applications/MAMP/htdocs/projetobd/application/controllers/employees.php on line 127`

Já corrigido:
- [x] Movimentação
- [x] Funcionários
- [x] Fornecedores
- [x] Produtos

**Comment by paulolieuthier** [comment]
Isso não era pra essa entrega!

**Comment by miguelarauj1o** [comment]
@ebl4, você pode resolver esta issue?

**Comment by paulolieuthier** [comment]
É bom testar agora.
