### ISSUE TITLE
Erro ao deletar um dado da base

### ISSUE THREAD

**Issue by miguelarauj1o** [LuizVasconcelos/ProjetoBD#3]
Quando é preciso deletar um dado qualquer, independente de qual seção estamos, é levantado o seguinte erro:

```
A Database Error Occurred
Error Number: 1451
Cannot delete or update a parent row: a foreign key constraint fails (`projetobd`.`telefone_fornecedor`, CONSTRAINT `telefone_fornecedor_ibfk_1` FOREIGN KEY (`cnpj`) REFERENCES `fornecedor` (`cnpj`))
DELETE FROM `fornecedor` WHERE `cnpj` = '770000000000'
Filename: /Applications/MAMP/htdocs/projetobd/models/suppliersmodel.php
Line Number: 52
```

Já corrigido:
- [x] Fornecedores
- [x] Movimentação (não precisa de correção)
- [x] Produtos
- [x] Funcionários

**Comment by paulolieuthier** [comment]
Eu vi, mas não era pra essa entrega!

**Comment by miguelarauj1o** [comment]
relaxa, tu é jovem. Eu vou resolver :+1:

**Comment by paulolieuthier** [comment]
Eu pensei que o professor tinha reclamado disso. Depois faz um resumo da apresentação e fala em algum lugar.

**Comment by miguelarauj1o** [comment]
@paulolieuthier, beleza!

**Comment by paulolieuthier** [comment]
Só a título de informação, esses dois commits anteriores foram feitos por Miguel.

**Comment by miguelarauj1o** [comment]
:+1:
