### ISSUE TITLE
Traduzir para PT-BR

### ISSUE THREAD

**Issue by miguelarauj1o** [LuizVasconcelos/ProjetoBD#6]
Existem algumas informações no projeto que são apresentadas ao usuário em inglês.

**Comment by miguelarauj1o** [comment]
@ebl4, você pode resolver esta issue?

**Comment by LuizVasconcelos** [comment]
Qualquer coisa, posso tentar fazer. Ainda tô com uma bronquinha no servidor, mas acho que dá para fazer ela, caso ele não possa.

**Comment by miguelarauj1o** [comment]
@LuizVasconcelos, tudo bem! :+1:

**Comment by paulolieuthier** [comment]
A questão das traduções é que em alguns lugares, como nos títulos das páginas, o título vem da capitalização da primeira letra do segmento da url.

**Comment by LuizVasconcelos** [comment]
Eu estou seguindo o tutorial do próprio Codeigniter sobre "línguas" pra fazer as traduções, qualquer bronca que tiver dando, dou um toque, já que não sei php (tô aprendendo ainda x.x), beleza?

**Comment by paulolieuthier** [comment]
Acho que esse tutorial deve ser complicado demais. A gente não quer fazer um site multi lingual, pode colocar em português hard-coded mesmo.

**Comment by LuizVasconcelos** [comment]
AAh, beleza então.

**Comment by LuizVasconcelos** [comment]
Commit parcial das traduções, ainda tem algumas coisas pra ajustar lá. Por favor, verifiquem se está tudo ok porque aqui tá sem funcionar ainda o login e tals (bronca no meu pc...)

**Comment by miguelarauj1o** [comment]
ba1535846cde1c9e8bf12aa4b2b66f4210246f9c and ee75d06d770142270cea62c7413148c85a466f6a

**Comment by miguelarauj1o** [comment]
@LuizVasconcelos, você testou o projeto após as mudanças?

**Comment by LuizVasconcelos** [comment]
Sim, aqui rodou normal. Só alterei os campos dos textos. Travou em alguma parte foi? Diz onde que eu vejo aqui.

**Comment by miguelarauj1o** [comment]
Nada, só pra saber. Então, depois fecha a issue.

**Comment by LuizVasconcelos** [comment]
Ok. Se alguém encontrar mais algo relacionado a tradução, só avisar que ajeito, beleza? Tô tentando ver como adicionar os telefones na list de funcionários.
