### ISSUE TITLE
Usar função lucro

### ISSUE THREAD

**Issue by miguelarauj1o** [LuizVasconcelos/ProjetoBD#8]
"ela mostra o resultado das movimentações de um período", @paulolieuthier

**Comment by ebl4** [comment]
Onde se encontra essa função lucro?

**Comment by paulolieuthier** [comment]
Foi a que tu fez, @ebl4.

**Comment by miguelarauj1o** [comment]
kkkkkkkkkkkkk

**Comment by ebl4** [comment]
Ah ta.. To em dúvida no uso dela, mas creio que é em cashflow

**Comment by paulolieuthier** [comment]
Também pensei assim, mas @m4nuela falou pra criar uma página chamada "Gerência". Tanto faz, desde que esteja funcionando.

**Comment by ebl4** [comment]
Já tem algum uso de alguma procedure? Porque aí poderia se basear neste exemplo

**Comment by paulolieuthier** [comment]
Tem, a listagem de todos os funcionários, fornecedores, produtos e movimentações são gerados por procedures.

https://github.com/LuizVasconcelos/ProjetoBD/blob/master/application/models/cashflowmodel.php#L26

**Comment by ebl4** [comment]
Boa. To seguindo por aí.

**Comment by m4nuela** [comment]
Foi, eu tinha sugerido colocar o valor do lucro na mema página principal do gerente, a q ele pode ver os relatório e tal...

**Comment by paulolieuthier** [comment]
To quase terminando.

**Comment by paulolieuthier** [comment]
Eu fiz em Movimentações mesmo, não tem tempo.

**Comment by miguelarauj1o** [comment]
:+1:
